-------CREATE TABLE-------

CREATE TABLE FOOD_DELIVERY(
ORDERID INT PRIMARY KEY,
ORDERDATE DATE,
CITY VARCHAR(20),
RESTAURANT VARCHAR(20),
CUISINE VARCHAR(20),
DELIVERY_TIME_MIN INT,
ORDERS INT,
AVGPRICE INT
);

-----INSERT THE DATA INTO TABLE------

INSERT INTO FOOD_DELIVERY VALUES
(5001,'2026-03-10','DELHI','SPICE HUB','INDIAN',30,2,350),
(5002,'2026-03-10','MUMBAI','PIZZA TOWN','ITALIAN',25,1,500),
(5003,'2026-03-11','BANGALORE','WOK EXPRESS','CHINESE',35,3,250),
(5004,'2026-03-11','DELHI','BURGERPOINT','FASTFOOD',20,2,200),
(5005,'2026-03-12','HYDERABAD','BIRYANI HOUSE','INDIAN',40,1,450),
(5006,'2026-03-12','MUMBAI','SPICE HUB','INDIAN',28,2,350),
(5007,'2026-03-13','BANGALORE','PIZZA TOWN','ITALIAN',32,1,500),
(5008,'2026-03-13','HYDERABAD','WOK EXPRESS','CHINESE',38,2,250),
(5009,'2026-03-14','DELHI','BIRYANI HOUSE','INDIAN',42,1,450),
(5010,'2026-03-14','MUMBAI','BURGER POINT','FASTFOOD',22,3,200)

----SEE THE WHOLE DATA------

SELECT * FROM FOOD_DELIVERY;

----TOTAL REVENUE----

SELECT 
  SUM(AVGPRICE*ORDERS) AS TOTALREVENUE
FROM FOOD_DELIVERY;

----REVENUE BY CUISINE-----

SELECT 
  CUISINE,
  SUM(AVGPRICE*ORDERS) AS TOTALREVENUE
FROM FOOD_DELIVERY
GROUP BY CUISINE
ORDER BY TOTALREVENUE DESC;

----AVERAGE DELIVERY TIME BY CUISINE-----

SELECT
  CUISINE,
  AVG(DELIVERY_TIME_MIN) AS AVERAGE_DELIVERY_TIME
FROM FOOD_DELIVERY
GROUP BY CUISINE
ORDER BY AVERAGE_DELIVERY_TIME DESC;

----TOP RESTAURANTS-----

SELECT 
  RESTAURANT,
  SUM(AVGPRICE*ORDERS) AS TOTALREVENUE
FROM FOOD_DELIVERY
GROUP BY RESTAURANT
ORDER BY TOTALREVENUE DESC;

-----REVENUE BY CUISINE----

SELECT 
  CUISINE,
  SUM(AVGPRICE*ORDERS) AS TOTALREVENUE
FROM FOOD_DELIVERY
GROUP BY CUISINE
ORDER BY TOTALREVENUE DESC;

-----REVENUE BY CITY-----

SELECT
  CITY,
  SUM(AVGPRICE*ORDERS) AS TOTALREVENUE
FROM FOOD_DELIVERY
GROUP BY CITY
ORDER BY TOTALREVENUE DESC;

-----ORDERS BY RESTAURANT----

SELECT
  RESTAURANT,
  ORDERS
FROM FOOD_DELIVERY
GROUP BY RESTAURANT,ORDERS
ORDER BY ORDERS DESC;

-----REVENUE BY ORDERDATE TREND------

SELECT 
  ORDERDATE,
  SUM(AVGPRICE*ORDERS) AS TOTALREVENUE
FROM FOOD_DELIVERY
GROUP BY ORDERDATE;
